sudo: required
services:
  - docker
  
before_install:
  - docker build -t harshadbhagwat/docker-react -f Dockerfile.dev .
   
script:
  - docker run harshadbhagwat/docker-react npm run test -- --coverage